config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/show", to: "users#show"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :lessons, only: [:create, :update, :show]
  resources :words, only: :index
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories, only: [:index, :show, :destroy] do
      resources :words, except: [:edit, :update]
    end
    resources :words, only: [:index, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons
  has_many :words
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action: load_category, except: [:index]
  def index
    @categories = Category.paginate page: params[:page], per_page: 5
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = "Category was updated"
      redirect_to admin_categories_url
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "#{@category.name} was deleted"
    redirect_to admin_categories_url
  end

  private
  def category_params
    params.require(:category).permit :name
  end
  def load_category
    @category = Category.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, :verify_normal

  def index
    @categories = Category.paginate page: params[:page], per_page:5
  end

  def show
    @category = Category.find params[:id]
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.submit "Edit Category", class: "btn btn-success" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, "Edit category" %>
<h1>Update Category</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, "Elearning-System" %>
<h1>Categories</h1>

<%= will_paginate @categories%>

<ul class="categories">
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, admin_categories_path, class: "pull-left" %>
      <div class="pull-right">
        <% if current_user.admin %>
          <%= link_to "Add word", new_admin_category_word_path(category.id), class: "btn btn-primary " %>
          <%= link_to "Edit", edit_admin_category_path(category.id), class: "btn btn-success " %>
          <%= link_to "Delete", [:admin, category], method: :delete, data: { confirm: "You sure?"}, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Start Lesson", "#", class: "btn btn-primary" %>
        <% end %>
      </div>
    </li>

  <% end %>
</ul>
<%= will_paginate @categories%>