config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get "/show", to: "users#show"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index, :show]
  resources :lessons, only: [:create, :update, :show]
  resources :words, only: :index
  namespace :admin do
    root "users#index"
    resources :users, only: [:index, :destroy]
    resources :categories, only: [:index, :show, :destroy] do
      resources :words, except: [:edit, :update]
    end
    resources :words, only: [:index, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lessons
  has_many :words
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action: load_category, except: [:index]
  def index
    @categories = Category.paginate page: params[:page], per_page: 5
  end

  def show
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = "Category was updated"
      redirect_to admin_categories_url
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "#{@category.name} was deleted"
    redirect_to admin_categories_url
  end

  private
  def category_params
    params.require(:category).permit :name
  end
  def load_category
    @category = Category.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, :verify_normal

  def index
    @categories = Category.paginate page: params[:page], per_page:5
  end

  def show
    @category = Category.find params[:id]
  end
end

app/views/categories/index.html.erb
<% provide :title, "Elearning-System" %>
<h1>Categories</h1>

<%= will_paginate @categories%>

<ul class="categories">
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category, class: "pull-left" %>
      <%= link_to "Start Lesson", lessons_path(category_id: category.id), :method => :post, class: "btn btn-primary pull-right" %>
    </li>

  <% end %>
</ul>
<%= will_paginate @categories%>

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <aside class="col-md-12">
    <section>
      <h1>
        <%= @category.name %>
      </h1>
      <div class="panel panel-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Words</th>
              <th scope="col">Answer</th>
            </tr>
          </thead>
          <tbody>
            <% @category.words.each do |word| %>
              <tr>
                <td><%= word.name %></td>
                <td>
                  <%= word.find_answers.name %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </section>
</div>